[package]
name = "appstream2dep11"
version = "0.1.0"
authors = ["stratact <stratact1@gmail.com>"]
edition = "2018"

[dependencies]
xml-rs = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
